version: 53
imports:
- projectPath: onedev/template
  revision: main
jobs:
- name: Release
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: true
    condition: SUCCESSFUL
    optional: false
  - type: UseTemplateStep
    name: set up cache
    templateName: set up cache
    condition: SUCCESSFUL
    optional: false
  - type: UseTemplateStep
    name: set build version
    templateName: set build version
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build & deploy
    runInContainer: true
    image: '@property:buildEnvironment@'
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        mvn deploy -Dmaven.deploy.username=@job_token@ -Dmaven.deploy.password=@secrets:maven-deploy-password@
    runAs: 0:0
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CreateTagStep
    name: create tag
    tagName: v@build_version@
    accessTokenSecret: onedev-token
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: main
    userMatch: anyone
  jobDependencies:
  - jobName: Scan Vulnerabilities
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 3600
- name: Scan Vulnerabilities
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - type: OsvSourceScannerStep
    name: scan
    recursive: true
    failThreshold: HIGH
    reportName: Dependency Vulnerabilities
    publishJSONReportAsArtifact: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: ScheduleTrigger
    cronExpression: 0 0 1 * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 3600
- name: Sync with GitHub
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: sync
    runInContainer: true
    image: alpine/git:1.0.7
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        git config --global --unset http.extraHeader
        git push -f https://robinshine:@secrets:github-token@@@github.com/theonedev/agent HEAD:main
    runAs: 0:0
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: main
    userMatch: anyone
    projects: onedev/agent
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 3600
