package io.onedev.agent;

public enum MessageTypes {

	HEART_BEAT, AGENT_DATA, ERROR, UPDATE, RESTART, STOP, UPDATE_ATTRIBUTES, 
	REQUEST, RESPONSE, JOB_LOG, CANCEL_JOB, REPORT_JOB_WORKSPACE, RESUME_JOB,
	SHELL_INPUT, SHELL_OUTPUT, SHELL_ERROR, SHELL_OPEN, SHELL_EXIT, SHELL_CLOSED, 
	SHELL_RESIZE
	
}
