package io.onedev.agent;

public enum MessageType {

	HEART_BEAT, AGENT_DATA, ERROR, UPDATE, RESTART, STOP, UPDATE_ATTRIBUTES, 
	REQUEST, RESPONSE, JOB_LOG, CANCEL_JOB, ALLOCATE_JOB_CACHES, 
	REPORT_JOB_WORKSPACE
	
}
