package io.onedev.agent;

public enum MessageTypes {

	HEART_BEAT, AGENT_DATA, ERROR, UPDATE, RESTART, STOP, UPDATE_ATTRIBUTES, 
	REQUEST, RESPONSE, JOB_LOG, CANCEL_JOB, REPORT_JOB_WORKDIR, RESUME_JOB,
	SHELL_OUTPUT, SHELL_OPEN, SHELL_TERMINATE, SHELL_EXIT
}
