package io.onedev.agent;

public enum MessageTypes {

	HEART_BEAT, AGENT_DATA, ERROR, UPDATE, RESTART, STOP, UPDATE_ATTRIBUTES, 
	REQUEST, RESPONSE, LOG, CANCEL_JOB, STOP_WORKSPACE, REPORT_JOB_WORKDIR, RESUME_JOB,
	JOB_SHELL_OUTPUT, JOB_SHELL_OPEN, JOB_SHELL_TERMINATE, JOB_SHELL_EXIT,
	WORKSPACE_SHELL_OUTPUT, WORKSPACE_SHELL_OPEN, WORKSPACE_SHELL_TERMINATE, WORKSPACE_SHELL_EXIT,
	WORKSPACE_SHELL_INPUT, WORKSPACE_SHELL_RESIZE,
	JOB_SHELL_INPUT, JOB_SHELL_RESIZE,
	DELETE_WORKSPACE
}
